steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image', '.']
  env:
  - 'PROJECT=$PROJECT_ID'
  - 'DATABASE_URL=$_DATABASE_URL'
  - 'BUCKET=$_BUCKET'
  - 'IMAGE_NAME=$_IMAGE_NAME'
images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME']
substitutions:
  _DATABASE_URL:
  _BUCKET:
  _IMAGE_NAME: