steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=serviceAccount.json.enc
  - --plaintext-file=serviceAccount.json
  - --location=global
  - --keyring=$_KEYRING
  - --key=$_KEY
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME', '.']
  env:
    - 'PROJECT=$PROJECT_ID'
    - 'DATABASE_URL=$_DATABASE_URL'
    - 'BUCKET=$_BUCKET'
    - 'IMAGE_NAME=$_IMAGE_NAME'
    - 'GOOGLE_APPLICATION_CREDENTIALS=secrets.json'
images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME']
substitutions:
  _DATABASE_URL:
  _BUCKET:
  _IMAGE_NAME: